import {createContext,useContext,useEffect,useMemo,useState,type FormEvent} from 'react'
import {Link,Navigate,Route,Routes,useNavigate,useParams} from 'react-router-dom'
import {api,ApiFailure,getSession,setSession} from './api'
import type {Plan,ScanResult,ScanSummary,UserSession} from './types'

type AuthValue={session:UserSession|null;save:(s:UserSession|null)=>void}
const AuthContext=createContext<AuthValue>({session:null,save:()=>{}})
const useAuth=()=>useContext(AuthContext)

const riskCopy:Record<string,string>={LOW:'Riesgo bajo observado',CAUTION:'Precaución',MEDIUM:'Riesgo medio',HIGH:'Riesgo alto',CRITICAL:'Riesgo crítico'}
const actionCopy:Record<string,string>={DO_NOT_PROCEED:'No continúes ni compartas datos. Verificá el origen por un canal oficial.',VERIFY_OFFICIAL_CHANNEL:'Verificá el pedido usando el sitio o teléfono oficial antes de actuar.',PROCEED_WITH_CAUTION:'Podés continuar con cautela y sin compartir información sensible.'}

function App(){
  const [session,saveState]=useState<UserSession|null>(()=>getSession())
  const value=useMemo(()=>({session,save:(next:UserSession|null)=>{setSession(next);saveState(next)}}),[session])
  return <AuthContext.Provider value={value}><Shell><Routes>
    <Route path="/" element={<Home/>}/><Route path="/acceso" element={<Access/>}/><Route path="/historial" element={<Protected><History/></Protected>}/>
    <Route path="/analisis/:id" element={<Protected><Detail/></Protected>}/><Route path="/planes" element={<Plans/>}/>
    <Route path="/admin" element={<Admin/>}/><Route path="/pago/:state" element={<PaymentState/>}/><Route path="*" element={<Navigate to="/" replace/>}/>
  </Routes></Shell></AuthContext.Provider>
}

function Shell({children}:{children:React.ReactNode}){
  const {session,save}=useAuth();const navigate=useNavigate()
  const logout=async()=>{const current=getSession();if(current)await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:current.refreshToken})}).catch(()=>{});save(null);navigate('/')}
  return <><header className="topbar"><Link className="brand" to="/"><span className="brand-mark">✓</span><span>ESCUDO <b>IA</b><small>un desarrollo de LIVEL V</small></span></Link>
    <nav><Link to="/">Analizar</Link><Link to="/planes">Planes</Link>{session&&<Link to="/historial">Historial</Link>}{session?.roles.some(r=>r.includes('ADMIN'))&&<Link to="/admin">ADMIN</Link>}{session?<button className="link-button" onClick={logout}>Salir</button>:<Link className="nav-cta" to="/acceso">Ingresar</Link>}</nav></header>
    <main>{children}</main><footer><div><strong>ESCUDO IA</strong><span>Protegemos decisiones digitales.</span></div><p>Herramienta de evaluación orientativa. No garantiza seguridad ni reemplaza soporte oficial o una denuncia.</p></footer></>
}

function Home(){return <>
  <section className="hero"><div className="hero-copy"><span className="eyebrow">CIBERSEGURIDAD EN LENGUAJE HUMANO</span><h1>Antes de hacer clic,<br/><em>verificá.</em></h1><p>Analizá mensajes, enlaces y capturas sospechosas. Recibí un índice de riesgo explicable y una recomendación clara en segundos.</p><div className="trust-row"><span>● Privacidad por defecto</span><span>● Sin abrir enlaces</span><span>● Resultado explicable</span></div></div><QuickScan/></section>
  <section className="how"><span className="eyebrow">CÓMO FUNCIONA</span><h2>Tres pasos. Una decisión más segura.</h2><div className="steps"><article><b>01</b><h3>Compartí la señal</h3><p>Pegá el mensaje o enlace, o subí una captura. Redactamos datos sensibles antes de analizar.</p></article><article><b>02</b><h3>Evaluamos el riesgo</h3><p>Combinamos heurísticas, contexto e indicadores versionados. La IA nunca decide sola.</p></article><article><b>03</b><h3>Actuá con contexto</h3><p>Entendé qué señales encontramos y qué conviene hacer antes de pagar o responder.</p></article></div></section>
  <section className="promise"><div><span className="eyebrow light">UNA PROMESA HONESTA</span><h2>No decimos “es seguro”.<br/>Te mostramos lo que observamos.</h2></div><p>La seguridad absoluta no existe. ESCUDO IA calcula riesgo, explica señales y recomienda una acción prudente para que decidas mejor.</p></section>
  </>}

function QuickScan(){
  const [type,setType]=useState<'TEXT'|'URL'|'IMAGE'>('TEXT');const [content,setContent]=useState('');const [file,setFile]=useState<File|null>(null);const [result,setResult]=useState<ScanResult|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('')
  const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');setResult(null);try{setResult(type==='IMAGE'&&file?await api.scanImage(file,content):type!=='IMAGE'?await api.scan(type,content):(()=>{throw new ApiFailure('FILE_REQUIRED','Seleccioná una imagen.')})())}catch(err){setError(err instanceof Error?err.message:'No pudimos analizar el contenido.')}finally{setLoading(false)}}
  return <div className="scan-wrap"><div className="scanner"><div className="scan-head"><div><span className="pulse"/>Quick Scan</div><small>ANÁLISIS ORIENTATIVO</small></div><div className="tabs"><button className={type==='TEXT'?'active':''} onClick={()=>setType('TEXT')}>Mensaje</button><button className={type==='URL'?'active':''} onClick={()=>setType('URL')}>Enlace</button><button className={type==='IMAGE'?'active':''} onClick={()=>setType('IMAGE')}>Captura</button></div><form onSubmit={submit}>
    {type==='IMAGE'?<><label className="upload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?file.name:'Elegí una captura PNG, JPG o WebP'}</span><small>Máximo 5 MB</small></label><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Contexto opcional: ¿dónde recibiste esta captura?"/></>:<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder={type==='TEXT'?'Pegá acá el mensaje que te genera dudas…':'https://ejemplo.com/enlace'} required maxLength={20000}/>} 
    {error&&<div className="alert error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?<><span className="spinner"/>Analizando señales…</>:'Analizar riesgo →'}</button><p className="privacy">◈ No visitamos enlaces ni guardamos análisis de invitados.</p></form></div>{result&&<ResultCard result={result}/>}</div>
}

function ResultCard({result}:{result:ScanResult}){return <section className={`result-card level-${result.level}`}><div className="result-top"><div className="score"><strong>{result.score}</strong><span>/100</span></div><div><span className="risk-label">{riskCopy[result.level]||result.level}</span><h2>{label(result.classification)}</h2><p>{result.summary}</p></div></div><div className="meter"><i style={{width:`${result.score}%`}}/></div><h3>Indicadores principales</h3>{result.indicators.length?<div className="indicators">{result.indicators.map((i,index)=><article key={i.type+index}><span>{i.severity}</span><div><strong>{label(i.type)}</strong><p>{i.explanation}</p></div></article>)}</div>:<div className="empty">No aparecieron señales significativas en este análisis.</div>}<div className="recommend"><b>Recomendación</b><p>{actionCopy[result.recommendedAction]||result.recommendedAction}</p></div><small className="engine">Motor {result.engineVersion} · Confianza {Math.round(result.confidence*100)}% · Evaluación orientativa</small></section>}

function Access(){const [register,setRegister]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const {session,save}=useAuth();const navigate=useNavigate();if(session)return <Navigate to="/historial" replace/>;const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{save(register?await api.register(email,password):await api.login(email,password));navigate('/historial')}catch(err){setError(err instanceof Error?err.message:'No pudimos ingresar.')}finally{setLoading(false)}};return <section className="auth-page"><div className="auth-card"><span className="brand-mark large">✓</span><span className="eyebrow">TU ESPACIO PROTEGIDO</span><h1>{register?'Creá tu cuenta':'Volvé a tu historial'}</h1><p>{register?'Guardá tus análisis y consultalos cuando los necesites.':'Ingresá para revisar tus análisis anteriores.'}</p><form onSubmit={submit}><label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={register?10:1} autoComplete={register?'new-password':'current-password'}/></label>{error&&<div className="alert error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?'Procesando…':register?'Crear cuenta':'Ingresar'}</button></form><button className="switch" onClick={()=>{setRegister(!register);setError('')}}>{register?'Ya tengo cuenta':'Quiero crear una cuenta'}</button></div></section>}

function Protected({children}:{children:React.ReactNode}){return useAuth().session?<>{children}</>:<Navigate to="/acceso" replace/>}

function History(){const [rows,setRows]=useState<ScanSummary[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);useEffect(()=>{api.history().then(r=>setRows(r.content)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);return <section className="page"><div className="page-title"><div><span className="eyebrow">MI ESCUDO</span><h1>Historial de análisis</h1><p>Volvé a consultar las señales detectadas y la recomendación.</p></div><Link className="primary" to="/">Nuevo análisis</Link></div>{error&&<div className="alert error">{error}</div>}{loading?<Skeleton/>:rows.length?<div className="history-list">{rows.map(r=><Link to={`/analisis/${r.id}`} key={r.id}><span className={`risk-dot ${r.level}`}/><div><strong>{r.type==='URL'?'Enlace':r.type==='IMAGE'?'Captura':'Mensaje'}</strong><small>{new Date(r.createdAt).toLocaleString('es-AR')}</small></div><b>{r.score}<small>/100</small></b><span className={`pill ${r.level}`}>{riskCopy[r.level]}</span><i>→</i></Link>)}</div>:<div className="empty-state"><div>⌁</div><h2>Todavía no hay análisis</h2><p>Probá el Quick Scan para ver tu primer resultado.</p><Link className="primary" to="/">Analizar ahora</Link></div>}</section>}

function Detail(){const {id}=useParams();const [result,setResult]=useState<ScanResult|null>(null);const [error,setError]=useState('');useEffect(()=>{if(id)api.detail(id).then(setResult).catch(e=>setError(e.message))},[id]);return <section className="page narrow"><Link className="back" to="/historial">← Volver al historial</Link>{error&&<div className="alert error">{error}</div>}{result?<ResultCard result={result}/>:!error&&<Skeleton/>}</section>}

function Plans(){const [plans,setPlans]=useState<Plan[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState('');const {session}=useAuth();const navigate=useNavigate();useEffect(()=>{api.plans().then(setPlans).catch(e=>setError(e.message))},[]);const checkout=async(code:string)=>{if(!session){navigate('/acceso');return}setBusy(code);setError('');try{const r=code==='SCAN_PREMIUM'?await api.scanCheckout():await api.subscribe(code);window.location.assign(r.checkoutUrl)}catch(e){setError(e instanceof Error?e.message:'No pudimos iniciar el pago.');setBusy('')}};return <section className="page plans-page"><div className="center-title"><span className="eyebrow">PLANES CLAROS</span><h1>Elegí cuánto querés proteger</h1><p>Los precios se leen desde la base de datos y pueden actualizarse sin redeploy.</p></div>{error&&<div className="alert error">{error}</div>}<div className="plan-grid">{plans.map(p=>{const features=safeArray(p.featuresJson);return <article className={p.code==='PERSONAL'?'featured':''} key={p.code}>{p.code==='PERSONAL'&&<span className="popular">MÁS ELEGIDO</span>}<h2>{p.name}</h2><div className="price"><b>{p.amount?new Intl.NumberFormat('es-AR',{style:'currency',currency:p.currency,maximumFractionDigits:0}).format(p.amount):'Gratis'}</b>{p.code==='PERSONAL'&&<small>/ mes</small>}</div><ul>{features.map(f=><li key={f}>✓ {f}</li>)}</ul><button className={p.code==='PERSONAL'?'primary wide':'secondary wide'} onClick={()=>checkout(p.code)} disabled={!!busy||p.code==='FREE'}>{p.code==='FREE'?'Plan actual':busy===p.code?'Conectando…':p.code==='SCAN_PREMIUM'?'Comprar un scan':'Elegir Personal'}</button></article>})}</div></section>}

function Admin(){const {session}=useAuth();const allowed=session?.roles.some(r=>r==='ROLE_ADMIN'||r==='ROLE_SUPER_ADMIN');const [users,setUsers]=useState<Array<{id:string;email:string;status:string;roles:string[]}>>([]);const [config,setConfig]=useState<Array<{component:string;weight:number;version:string}>>([]);const [message,setMessage]=useState('');useEffect(()=>{if(allowed){api.adminUsers().then(r=>setUsers(r.content));api.riskConfig().then(setConfig)}},[allowed]);if(!session)return <Navigate to="/acceso" replace/>;if(!allowed)return <Navigate to="/" replace/>;const save=async()=>{setMessage('');try{await api.saveRiskConfig(config.map(({component,weight})=>({component,weight})));setMessage('Configuración guardada y auditada.')}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.')}};return <section className="page"><div className="page-title"><div><span className="eyebrow">OPERACIÓN</span><h1>ADMIN ESCUDO</h1></div></div><div className="admin-grid"><article className="admin-panel"><h2>Risk Engine</h2><p>Los pesos deben sumar 100. Todo cambio genera una nueva versión.</p>{config.map((row,i)=><label className="weight" key={row.component}><span>{label(row.component)}</span><input type="number" min="0" max="100" value={row.weight} onChange={e=>setConfig(config.map((r,j)=>j===i?{...r,weight:Number(e.target.value)}:r))}/><small>%</small></label>)}<div className="total">Total <b>{config.reduce((a,b)=>a+b.weight,0)}%</b></div><button className="primary" onClick={save}>Guardar configuración</button>{message&&<p className="admin-message">{message}</p>}</article><article className="admin-panel"><h2>Usuarios recientes</h2><div className="users">{users.map(u=><div key={u.id}><span>{u.email.slice(0,1).toUpperCase()}</span><div><b>{u.email}</b><small>{u.roles.join(' · ')}</small></div><i>{u.status}</i></div>)}</div></article></div></section>}

function PaymentState(){const {state}=useParams();const success=state==='exito';return <section className="auth-page"><div className="auth-card payment"><div className={success?'payment-icon success':'payment-icon'}>{success?'✓':'…'}</div><span className="eyebrow">MERCADO PAGO</span><h1>{success?'Recibimos tu operación':state==='pendiente'?'El pago está pendiente':'El pago no se completó'}</h1><p>{success?'Estamos esperando la confirmación segura del webhook. El redirect por sí solo no activa beneficios.':'Podés volver a intentarlo desde la sección de planes.'}</p><Link className="primary wide" to="/planes">Volver a planes</Link></div></section>}

function Skeleton(){return <div className="skeleton"><i/><i/><i/></div>}
function label(value:string){return value.toLowerCase().split('_').map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(' ')}
function safeArray(value:string):string[]{try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[]}catch{return []}}

export default App
